<?php

return [
    'questions' => [
        [
            'id' => 1,
            'question' => 'Aktivitas seperti apa yang membuat kamu merasa sangat menikmati prosesnya sampai lupa waktu?',
            'context' => [
                'aktivitas',
                'kegiatan',
                'hobi',
                'belajar',
                'membuat',
                'eksplorasi',
                'memecahkan',
                'coding',
                'desain',
                'analisis',
                'menulis',
                'menggambar',
                'olahraga',
                'diskusi',
                'mengajar',
                'meneliti',
                'merakit',
                'eksperimen',
                'bermain',
                'musik',
                'foto',
                'video',
                'game',
                'aplikasi',
            ],
            'follow_up' => 'Boleh ceritakan lebih spesifik tentang aktivitas atau kegiatan yang kamu sukai?',
        ],
        [
            'id' => 2,
            'question' => 'Saat menghadapi suatu masalah, kamu biasanya lebih suka mencoba langsung, menganalisis dulu, berdiskusi, atau mencari cara lain?',
            'context' => [
                'masalah',
                'analisis',
                'diskusi',
                'mencoba',
                'solusi',
                'berpikir',
                'sendiri',
                'tim',
                'langsung',
                'riset',
                'tanya',
                'baca',
                'coba',
                'pahami',
                'logika',
                'strategi',
                'kolaborasi',
                'mandiri',
                'eksekusi',
            ],
            'follow_up' => 'Coba ceritakan lebih detail — saat ada masalah, apa langkah pertama yang biasanya kamu ambil?',
        ],
        [
            'id' => 3,
            'question' => 'Lingkungan belajar atau kerja seperti apa yang membuat kamu merasa nyaman dan produktif?',
            'context' => [
                'lingkungan',
                'suasana',
                'tenang',
                'ramai',
                'sendiri',
                'tim',
                'teratur',
                'fleksibel',
                'bebas',
                'struktur',
                'kantor',
                'rumah',
                'kampus',
                'studio',
                'lab',
                'lapangan',
                'outdoor',
                'indoor',
                'fokus',
                'diskusi',
                'kolaborasi',
                'mandiri',
                'nyaman',
            ],
            'follow_up' => 'Apakah kamu lebih suka suasana yang tenang dan teratur, atau yang dinamis dan banyak interaksi?',
        ],
        [
            'id' => 4,
            'question' => 'Ketika mengerjakan sesuatu, bagian mana yang paling kamu nikmati: membuat, menganalisis, membantu, memimpin, mengatur, atau lainnya?',
            'context' => [
                'membuat',
                'analisis',
                'membantu',
                'memimpin',
                'mengatur',
                'mencipta',
                'meneliti',
                'mengajar',
                'strategi',
                'detail',
                'eksekusi',
                'planning',
                'brainstorming',
                'presentasi',
                'evaluasi',
                'desain',
                'coding',
                'riset',
                'koordinasi',
                'review',
            ],
            'follow_up' => 'Dari semuanya, mana yang paling bikin kamu semangat?',
        ],
        [
            'id' => 5,
            'question' => 'Menurutmu, kemampuan atau cara kerja apa yang paling sering kamu andalkan?',
            'context' => [
                'kemampuan',
                'skill',
                'andalan',
                'logika',
                'kreativitas',
                'komunikasi',
                'analisis',
                'teliti',
                'cepat',
                'adaptif',
                'teknis',
                'sosial',
                'problem solving',
                'leadership',
                'teamwork',
                'critical thinking',
                'detail',
                'strategi',
                'empati',
                'negosiasi',
                'presentasi',
            ],
            'follow_up' => 'Apakah kemampuan itu kamu dapat dari bakat alami, belajar, atau pengalaman?',
        ],
        [
            'id' => 6,
            'question' => 'Topik atau bidang apa yang paling sering membuat kamu penasaran dan ingin mempelajarinya lebih jauh?',
            'context' => [
                'teknologi',
                'sains',
                'seni',
                'bisnis',
                'kesehatan',
                'pendidikan',
                'lingkungan',
                'sosial',
                'politik',
                'ekonomi',
                'filsafat',
                'sejarah',
                'olahraga',
                'musik',
                'film',
                'game',
                'coding',
                'desain',
                'fotografi',
                'jurnalistik',
                'hukum',
                'psikologi',
                'matematika',
                'fisika',
                'kimia',
                'biologi',
                'astronomi',
                'robotika',
                'AI',
                'data',
                'literatur',
                'hubungan internasional',
                'diplomasi',
                'komunikasi',
                'budaya',
                'pariwisata',
                'kriminologi',
                'pemerintahan',
            ],
            'follow_up' => 'Boleh ceritakan lebih spesifik — apa yang bikin topik itu menarik buat kamu?',
        ],

        [
            'id' => 7,
            'question' => 'Jika bebas memilih pekerjaan di masa depan tanpa memikirkan gaji atau nilai, pekerjaan seperti apa yang ingin kamu lakukan?',
            'context' => [
                'pekerjaan',
                'karier',
                'profesi',
                'dokter',
                'guru',
                'insinyur',
                'programmer',
                'desainer',
                'seniman',
                'musisi',
                'penulis',
                'jurnalis',
                'pengusaha',
                'manajer',
                'konsultan',
                'peneliti',
                'ilmuwan',
                'arsitek',
                'pilot',
                'koki',
                'fotografer',
                'videografer',
                'streamer',
                'youtuber',
                'bekerja sendiri',
                'freelance',
                'startup',
                'perusahaan besar',
                'membantu orang',
                'menciptakan',
                'memimpin',
                'menganalisis',
                'diplomat',
                'pengacara',
                'psikolog',
                'konselor',
                'pegawai pemerintahan',
                'analis kebijakan',
                'politisi',
                'hubungan masyarakat',
                'pekerja sosial',
            ],
            'follow_up' => 'Apa yang paling menarik dari pekerjaan itu buat kamu?',
        ],
        [
            'id' => 8,
            'question' => 'Pekerjaan atau aktivitas seperti apa yang paling menarik untuk kamu bayangkan dilakukan setiap hari?',
            'context' => [
                'aktivitas',
                'rutinitas',
                'setiap hari',
                'membuat',
                'menganalisis',
                'membantu',
                'memimpin',
                'mengajar',
                'menulis',
                'menggambar',
                'coding',
                'desain',
                'diskusi',
                'presentasi',
                'riset',
                'eksperimen',
                'koordinasi',
                'planning',
                'brainstorming',
                'review',
                'testing',
                'debugging',
                'editing',
                'fotografi',
                'videografi',
                'menjahit',
                'merakit',
                'memasak',
                'berkebun',
                'olahraga',
                'meditasi',
                'bernegosiasi',
                'melakukan wawancara',
                'melakukan konseling',
                'menulis artikel',
                'berbicara di depan umum',
                'menyusun strategi',
                'membangun relasi',
                'observasi lapangan',
                'melakukan advokasi',
            ],
            'follow_up' => 'Kenapa aktivitas itu yang paling kamu bayangkan?',
        ],
    ],

    'blacklist' => [
        'gatau',
        'ga tau',
        'tidak tahu',
        'nggak tau',
        'bingung',
        'terserah',
        'apa aja',
        'entah',
        'terserahlah',
        'ntah',
        'gak tau',
    ],

    'min_words' => 3,
];
